In [1]:
import numpy as np

import pandas as pd

from pandas import Series, DataFrame 

 how to merge 2 DataFrame 

In [2]:
dframe1 = DataFrame({'key': ['X','Y','Z','Y','Z','X'], 'data_set_1': np.arange(6)})
dframe1

key  data_set_1
0   X           0
1   Y           1
2   Z           2
3   Y           3
4   Z           4
5   X           5

In [3]:
dframe2 = DataFrame({'key': ['Y','X','V'], 'data_set_2': ['1','3','4']})


In [4]:
dframe2

key data_set_2
0   Y          1
1   X          3
2   V          4

In [5]:
pd.merge(dframe1,dframe2)

key  data_set_1 data_set_2
0   X           0          3
1   X           5          3
2   Y           1          1
3   Y           3          1

In [6]:
pd.merge(dframe1,dframe2,on = 'key')

key  data_set_1 data_set_2
0   X           0          3
1   X           5          3
2   Y           1          1
3   Y           3          1

In [7]:
pd.merge(dframe1,dframe2, on = 'key', how ='left')

key  data_set_1 data_set_2
0   X           0          3
1   Y           1          1
2   Z           2        NaN
3   Y           3          1
4   Z           4        NaN
5   X           5          3

In [8]:
dframe1

key  data_set_1
0   X           0
1   Y           1
2   Z           2
3   Y           3
4   Z           4
5   X           5

In [9]:
dframe2


key data_set_2
0   Y          1
1   X          3
2   V          4

In [10]:
pd.merge(dframe1,dframe2,on = 'key', how = 'outer')

key  data_set_1 data_set_2
0   X         0.0          3
1   X         5.0          3
2   Y         1.0          1
3   Y         3.0          1
4   Z         2.0        NaN
5   Z         4.0        NaN
6   V         NaN          4

In [11]:
# read up on merge from the pandas library

merge on index

In [12]:
df_left = DataFrame({'key':['Wed','Thu','Wed','Mon','Tue','Mon'], 'data': range(6)})
df_left

key  data
0  Wed     0
1  Thu     1
2  Wed     2
3  Mon     3
4  Tue     4
5  Mon     5

In [13]:
df_right = DataFrame({'group_data':[10,20]}, index = ['Mon','Tue'])
df_right

group_data
Mon          10
Tue          20

In [14]:
pd.merge(df_left,df_right,left_on= 'key', right_index=True)

key  data  group_data
3  Mon     3          10
5  Mon     5          10
4  Tue     4          20

In [15]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
np.concatenate([arr1,arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [17]:
np.concatenate([arr1,arr1], axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
ser1 = Series([1,2,3], index = ['G','B','A'])

ser2 = Series([4,5], index= ['V','U'])

In [19]:
ser1

G    1
B    2
A    3
dtype: int64

In [20]:
ser2

V    4
U    5
dtype: int64

In [21]:
pd.concat([ser1,ser2])

G    1
B    2
A    3
V    4
U    5
dtype: int64

In [22]:
pd.concat([ser1,ser2], axis = 1)

0    1
G  1.0  NaN
B  2.0  NaN
A  3.0  NaN
V  NaN  4.0
U  NaN  5.0

In [23]:
pd.concat([ser1,ser2], keys = ['cat1','cat2'])

cat1  G    1
      B    2
      A    3
cat2  V    4
      U    5
dtype: int64

In [24]:
dframe4 = DataFrame(np.random.randn(4,3), columns = ['NY','LA','SA'])

In [25]:
dframe6 =  DataFrame(np.random.randn(3,3), columns = ['FC','LA','SA'])

In [26]:
dframe4

NY        LA        SA
0 -0.021727  0.116201  1.001793
1 -0.783410 -1.456907 -0.644491
2  0.399884  0.040907  1.985639
3  0.843759  0.445659 -0.461201

In [27]:
dframe6

FC        LA        SA
0  1.140671 -0.145963  1.158436
1 -0.298428 -2.058199  0.133848
2 -0.128243  0.162716 -2.789283

In [28]:
pd.concat([dframe4,dframe6], ignore_index= True)

NY        LA        SA        FC
0 -0.021727  0.116201  1.001793       NaN
1 -0.783410 -1.456907 -0.644491       NaN
2  0.399884  0.040907  1.985639       NaN
3  0.843759  0.445659 -0.461201       NaN
4       NaN -0.145963  1.158436  1.140671
5       NaN -2.058199  0.133848 -0.298428
6       NaN  0.162716 -2.789283 -0.128243